CREATE DATABASE campusland;

USE campusland;

CREATE TABLE pais(

idPais INT (10) NOT NULL PRIMARY KEY COMMENT 'ID PAIS LLAVE PRIMARIA',

nombrePais INT(10) COMMENT 'NOMBRE PAIS'

);



CREATE TABLE departamento(

idDep INT(10) NOT NULL PRIMARY KEY COMMENT 'ID DEPARTAMENTO',

nombreDep VARCHAR(50) COMMENT 'NOMBRE DEPARTAMENTO',

idPais INT(10) COMMENT 'ID TABLA PAIS'

);



CREATE TABLE region(

idReg INT(10) NOT NULL PRIMARY KEY COMMENT ' ID REGION ',

nombreReg VARCHAR(60) COMMENT 'NOMBRE REGION',

idDep INT(10) COMMENT 'ID DEPARTAMENTO'

);



CREATE TABLE campers(

idCamper VARCHAR(20) NOT NULL PRIMARY KEY COMMENT 'ID CAMPER',

nombreCamper VARCHAR(50) COMMENT 'NOMBRE CAMPER',

apellidoCamper VARCHAR(50) COMMENT 'APELLIDO CAMPER',

fechaNac DATETIME COMMENT 'FECHA NACIMIENTO',

idReg INT(10) COMMENT 'ID REGION'

);

ALTER TABLE pais FOREIGN KEY(nombrePais) REFERENCES departamento(idPais);

ALTER TABLE departamento ADD CONSTRAINT idDep FOREIGN KEY (idDep) REFERENCES region(idDep);

ALTER TABLE region ADD CONSTRAINT idReg FOREIGN KEY (idReg) REFERENCE campers(idReg);